// Koen Van Caekenberghe, ChipDesign B.V., 06.2026
/* Generated by Yosys 0.65 (git sha1 b85cad634, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* top =  1  *)
(* src = "../spi_slave.v:17.1-207.10" *)
module SPI_Slave(Clk, iRST_N, SCK, MOSI, SSEL, MISO, Add2_in, Data2_out, debug);
  (* src = "../spi_slave.v:19.8-19.11" *)
  input Clk;
  wire Clk;
  (* src = "../spi_slave.v:20.8-20.14" *)
  input iRST_N;
  wire iRST_N;
  (* src = "../spi_slave.v:22.8-22.11" *)
  input SCK;
  wire SCK;
  (* src = "../spi_slave.v:23.8-23.12" *)
  input MOSI;
  wire MOSI;
  (* src = "../spi_slave.v:24.8-24.12" *)
  input SSEL;
  wire SSEL;
  (* src = "../spi_slave.v:25.13-25.17" *)
  output MISO;
  reg MISO;
  (* src = "../spi_slave.v:27.14-27.21" *)
  input [7:0] Add2_in;
  wire [7:0] Add2_in;
  (* src = "../spi_slave.v:28.19-28.28" *)
  output [7:0] Data2_out;
  reg [7:0] Data2_out;
  (* src = "../spi_slave.v:30.19-30.24" *)
  output [7:0] debug;
  wire [7:0] debug;
  (* src = "../spi_slave.v:43.1-205.4" *)
  wire [3:0] _0000_;
  (* src = "../spi_slave.v:43.1-205.4" *)
  wire [7:0] _0001_;
  (* src = "../spi_slave.v:43.1-205.4" *)
  wire [7:0] _0002_;
  (* src = "../spi_slave.v:43.1-205.4" *)
  wire [7:0] _0003_;
  (* src = "../spi_slave.v:43.1-205.4" *)
  wire [2:0] _0004_;
  (* src = "../spi_slave.v:43.1-205.4" *)
  wire _0005_;
  (* src = "../spi_slave.v:43.1-205.4" *)
  (* unused_bits = "5 6 7" *)
  wire [7:0] _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire [3:0] _0060_;
  wire [1:0] _0061_;
  wire [3:0] _0062_;
  wire [1:0] _0063_;
  wire [3:0] _0064_;
  wire [1:0] _0065_;
  wire [3:0] _0066_;
  wire [1:0] _0067_;
  wire [1:0] _0068_;
  wire [1:0] _0069_;
  wire [2:0] _0070_;
  wire [1:0] _0071_;
  wire [2:0] _0072_;
  wire [1:0] _0073_;
  wire [2:0] _0074_;
  wire [1:0] _0075_;
  wire [2:0] _0076_;
  wire [1:0] _0077_;
  wire [2:0] _0078_;
  wire [1:0] _0079_;
  wire [1:0] _0080_;
  wire [1:0] _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire [1:0] _0086_;
  wire _0087_;
  wire _0088_;
  wire [1:0] _0089_;
  wire _0090_;
  wire [1:0] _0091_;
  wire [1:0] _0092_;
  wire _0093_;
  wire [1:0] _0094_;
  wire _0095_;
  wire [1:0] _0096_;
  wire _0097_;
  wire [1:0] _0098_;
  wire _0099_;
  wire [1:0] _0100_;
  wire _0101_;
  wire [1:0] _0102_;
  wire [1:0] _0103_;
  wire [1:0] _0104_;
  wire _0105_;
  wire [3:0] _0106_;
  wire [1:0] _0107_;
  wire _0108_;
  wire [3:0] _0109_;
  wire [1:0] _0110_;
  wire _0111_;
  wire [3:0] _0112_;
  wire [1:0] _0113_;
  wire _0114_;
  wire [3:0] _0115_;
  wire [1:0] _0116_;
  wire _0117_;
  wire [3:0] _0118_;
  wire [1:0] _0119_;
  wire _0120_;
  wire [3:0] _0121_;
  wire [1:0] _0122_;
  wire _0123_;
  wire [1:0] _0124_;
  wire _0125_;
  wire [1:0] _0126_;
  wire _0127_;
  wire [1:0] _0128_;
  wire _0129_;
  wire [1:0] _0130_;
  wire _0131_;
  wire [1:0] _0132_;
  wire _0133_;
  wire [3:0] _0134_;
  wire [1:0] _0135_;
  wire _0136_;
  wire [3:0] _0137_;
  wire [1:0] _0138_;
  wire _0139_;
  wire [3:0] _0140_;
  wire [1:0] _0141_;
  wire _0142_;
  wire [3:0] _0143_;
  wire [1:0] _0144_;
  wire _0145_;
  wire [3:0] _0146_;
  wire [1:0] _0147_;
  wire _0148_;
  wire [3:0] _0149_;
  wire [1:0] _0150_;
  wire _0151_;
  wire [3:0] _0152_;
  wire [1:0] _0153_;
  wire _0154_;
  wire [3:0] _0155_;
  wire [1:0] _0156_;
  wire _0157_;
  wire [3:0] _0158_;
  wire [1:0] _0159_;
  wire _0160_;
  wire _0161_;
  wire [1:0] _0162_;
  wire _0163_;
  wire [1:0] _0164_;
  wire _0165_;
  wire [1:0] _0166_;
  wire _0167_;
  wire [1:0] _0168_;
  wire _0169_;
  wire [1:0] _0170_;
  wire _0171_;
  wire [1:0] _0172_;
  wire _0173_;
  wire _0174_;
  wire [1:0] _0175_;
  wire _0176_;
  wire [3:0] _0177_;
  wire [1:0] _0178_;
  wire _0179_;
  wire [3:0] _0180_;
  wire [1:0] _0181_;
  wire _0182_;
  wire [3:0] _0183_;
  wire [1:0] _0184_;
  wire [1:0] _0185_;
  wire [1:0] _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  (* src = "../spi_slave.v:139.9-139.25" *)
  wire _0346_;
  (* src = "../spi_slave.v:145.28-145.43" *)
  wire _0347_;
  (* src = "../spi_slave.v:176.10-176.25" *)
  wire _0348_;
  wire [7:0] _0349_;
  wire [7:0] _0350_;
  wire [3:0] _0351_;
  wire [3:0] _0352_;
  wire [3:0] _0353_;
  wire [3:0] _0354_;
  wire [3:0] _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire [2:0] _0375_;
  wire [2:0] _0376_;
  wire [2:0] _0377_;
  wire [7:0] _0378_;
  wire [7:0] _0379_;
  wire [7:0] _0380_;
  wire [7:0] _0381_;
  (* force_downto = 32'd1 *)
  (* src = "../spi_slave.v:186.17-186.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [31:0] _0382_;
  (* force_downto = 32'd1 *)
  (* src = "../spi_slave.v:186.17-186.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _0383_;
  (* force_downto = 32'd1 *)
  (* src = "../spi_slave.v:186.17-186.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4" *)
  wire [31:0] _0384_;
  (* src = "../spi_slave.v:40.63-40.70" *)
  wire [7:0] Add_SPI;
  (* src = "../spi_slave.v:39.11-39.17" *)
  reg [3:0] BitCnt;
  (* src = "../spi_slave.v:40.39-40.49" *)
  reg [7:0] DataToSend;
  (* src = "../spi_slave.v:40.25-40.37" *)
  reg [7:0] Data_fromSPI;
  (* src = "../spi_slave.v:40.51-40.61" *)
  reg [7:0] Data_toSPI;
  (* src = "../spi_slave.v:36.17-36.28" *)
  reg MOSI_delay0;
  (* src = "../spi_slave.v:35.21-35.36" *)
  reg MOSI_metastable;
  (* src = "../spi_slave.v:40.11-40.23" *)
  reg [7:0] ReceivedByte;
  (* src = "../spi_slave.v:33.11-33.20" *)
  reg [7:0] Register0;
  (* src = "../spi_slave.v:33.22-33.31" *)
  reg [7:0] Register1;
  (* src = "../spi_slave.v:33.33-33.42" *)
  reg [7:0] Register2;
  (* src = "../spi_slave.v:33.44-33.53" *)
  reg [7:0] Register3;
  (* src = "../spi_slave.v:33.55-33.64" *)
  reg [7:0] Register4;
  (* src = "../spi_slave.v:33.66-33.75" *)
  reg [7:0] Register5;
  (* src = "../spi_slave.v:33.77-33.86" *)
  reg [7:0] Register6;
  (* src = "../spi_slave.v:33.88-33.97" *)
  reg [7:0] Register7;
  (* src = "../spi_slave.v:38.11-38.14" *)
  reg RnW;
  (* src = "../spi_slave.v:36.5-36.15" *)
  reg SCK_delay0;
  (* src = "../spi_slave.v:37.5-37.15" *)
  reg SCK_delay1;
  (* src = "../spi_slave.v:35.5-35.19" *)
  reg SCK_metastable;
  (* src = "../spi_slave.v:41.11-41.20" *)
  reg [2:0] SPI_State;
  (* src = "../spi_slave.v:36.30-36.41" *)
  reg SSEL_delay0;
  (* src = "../spi_slave.v:37.17-37.28" *)
  reg SSEL_delay1;
  (* src = "../spi_slave.v:35.38-35.53" *)
  reg SSEL_metastable;
  (* src = "../spi_slave.v:38.5-38.9" *)
  reg WrEn;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data2_out[0] <= 1'h0;
    else Data2_out[0] <= _0001_[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data2_out[1] <= 1'h0;
    else Data2_out[1] <= _0001_[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data2_out[2] <= 1'h0;
    else Data2_out[2] <= _0001_[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data2_out[3] <= 1'h0;
    else Data2_out[3] <= _0001_[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data2_out[4] <= 1'h0;
    else Data2_out[4] <= _0001_[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data2_out[5] <= 1'h0;
    else Data2_out[5] <= _0001_[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data2_out[6] <= 1'h0;
    else Data2_out[6] <= _0001_[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data2_out[7] <= 1'h0;
    else Data2_out[7] <= _0001_[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) SCK_metastable <= 1'h0;
    else SCK_metastable <= SCK;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) MOSI_metastable <= 1'h0;
    else MOSI_metastable <= MOSI;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) SSEL_metastable <= 1'h0;
    else SSEL_metastable <= SSEL;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) SCK_delay0 <= 1'h0;
    else SCK_delay0 <= SCK_metastable;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) MOSI_delay0 <= 1'h0;
    else MOSI_delay0 <= MOSI_metastable;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) SSEL_delay0 <= 1'h0;
    else SSEL_delay0 <= SSEL_metastable;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) SCK_delay1 <= 1'h0;
    else SCK_delay1 <= SCK_delay0;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) SSEL_delay1 <= 1'h0;
    else SSEL_delay1 <= SSEL_delay0;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) WrEn <= 1'h0;
    else WrEn <= _0005_;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) SPI_State[0] <= 1'h0;
    else if (_0046_) SPI_State[0] <= _0004_[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) SPI_State[1] <= 1'h0;
    else if (_0046_) SPI_State[1] <= _0004_[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) SPI_State[2] <= 1'h0;
    else if (_0046_) SPI_State[2] <= _0004_[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) ReceivedByte[0] <= 1'h0;
    else if (_0045_) ReceivedByte[0] <= _0003_[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) ReceivedByte[1] <= 1'h0;
    else if (_0045_) ReceivedByte[1] <= _0003_[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) ReceivedByte[2] <= 1'h0;
    else if (_0045_) ReceivedByte[2] <= _0003_[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) ReceivedByte[3] <= 1'h0;
    else if (_0045_) ReceivedByte[3] <= _0003_[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) ReceivedByte[4] <= 1'h0;
    else if (_0045_) ReceivedByte[4] <= _0003_[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) ReceivedByte[5] <= 1'h0;
    else if (_0045_) ReceivedByte[5] <= _0003_[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) ReceivedByte[6] <= 1'h0;
    else if (_0045_) ReceivedByte[6] <= _0003_[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) ReceivedByte[7] <= 1'h0;
    else if (_0045_) ReceivedByte[7] <= _0003_[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_fromSPI[0] <= 1'h0;
    else if (_0044_) Data_fromSPI[0] <= _0002_[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_fromSPI[1] <= 1'h0;
    else if (_0044_) Data_fromSPI[1] <= _0002_[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_fromSPI[2] <= 1'h0;
    else if (_0044_) Data_fromSPI[2] <= _0002_[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_fromSPI[3] <= 1'h0;
    else if (_0044_) Data_fromSPI[3] <= _0002_[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_fromSPI[4] <= 1'h0;
    else if (_0044_) Data_fromSPI[4] <= _0002_[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_fromSPI[5] <= 1'h0;
    else if (_0044_) Data_fromSPI[5] <= _0002_[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_fromSPI[6] <= 1'h0;
    else if (_0044_) Data_fromSPI[6] <= _0002_[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_fromSPI[7] <= 1'h0;
    else if (_0044_) Data_fromSPI[7] <= _0002_[7];
  reg \Add_SPI_reg[0] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \Add_SPI_reg[0]  <= 1'h0;
    else if (_0029_) \Add_SPI_reg[0]  <= ReceivedByte[0];
  assign Add_SPI[0] = \Add_SPI_reg[0] ;
  reg \Add_SPI_reg[1] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \Add_SPI_reg[1]  <= 1'h0;
    else if (_0029_) \Add_SPI_reg[1]  <= ReceivedByte[1];
  assign Add_SPI[1] = \Add_SPI_reg[1] ;
  reg \Add_SPI_reg[2] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \Add_SPI_reg[2]  <= 1'h0;
    else if (_0029_) \Add_SPI_reg[2]  <= ReceivedByte[2];
  assign Add_SPI[2] = \Add_SPI_reg[2] ;
  reg \Add_SPI_reg[3] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \Add_SPI_reg[3]  <= 1'h0;
    else if (_0029_) \Add_SPI_reg[3]  <= ReceivedByte[3];
  assign Add_SPI[3] = \Add_SPI_reg[3] ;
  reg \Add_SPI_reg[4] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \Add_SPI_reg[4]  <= 1'h0;
    else if (_0029_) \Add_SPI_reg[4]  <= ReceivedByte[4];
  assign Add_SPI[4] = \Add_SPI_reg[4] ;
  reg \Add_SPI_reg[5] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \Add_SPI_reg[5]  <= 1'h0;
    else if (_0029_) \Add_SPI_reg[5]  <= ReceivedByte[5];
  assign Add_SPI[5] = \Add_SPI_reg[5] ;
  reg \Add_SPI_reg[6] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \Add_SPI_reg[6]  <= 1'h0;
    else if (_0029_) \Add_SPI_reg[6]  <= ReceivedByte[6];
  assign Add_SPI[6] = \Add_SPI_reg[6] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register3[0] <= 1'h1;
    else if (_0043_) Register3[0] <= Data_fromSPI[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register3[1] <= 1'h0;
    else if (_0043_) Register3[1] <= Data_fromSPI[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register3[2] <= 1'h1;
    else if (_0043_) Register3[2] <= Data_fromSPI[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register3[3] <= 1'h1;
    else if (_0043_) Register3[3] <= Data_fromSPI[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register3[4] <= 1'h0;
    else if (_0043_) Register3[4] <= Data_fromSPI[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register3[5] <= 1'h0;
    else if (_0043_) Register3[5] <= Data_fromSPI[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register3[6] <= 1'h0;
    else if (_0043_) Register3[6] <= Data_fromSPI[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register3[7] <= 1'h0;
    else if (_0043_) Register3[7] <= Data_fromSPI[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) RnW <= 1'h0;
    else if (_0029_) RnW <= ReceivedByte[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register2[0] <= 1'h0;
    else if (_0042_) Register2[0] <= Data_fromSPI[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register2[1] <= 1'h0;
    else if (_0042_) Register2[1] <= Data_fromSPI[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register2[2] <= 1'h1;
    else if (_0042_) Register2[2] <= Data_fromSPI[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register2[3] <= 1'h1;
    else if (_0042_) Register2[3] <= Data_fromSPI[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register2[4] <= 1'h0;
    else if (_0042_) Register2[4] <= Data_fromSPI[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register2[5] <= 1'h0;
    else if (_0042_) Register2[5] <= Data_fromSPI[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register2[6] <= 1'h0;
    else if (_0042_) Register2[6] <= Data_fromSPI[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register2[7] <= 1'h0;
    else if (_0042_) Register2[7] <= Data_fromSPI[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register7[0] <= 1'h0;
    else if (_0041_) Register7[0] <= Data_fromSPI[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register7[1] <= 1'h0;
    else if (_0041_) Register7[1] <= Data_fromSPI[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register7[2] <= 1'h0;
    else if (_0041_) Register7[2] <= Data_fromSPI[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register7[3] <= 1'h0;
    else if (_0041_) Register7[3] <= Data_fromSPI[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register7[4] <= 1'h1;
    else if (_0041_) Register7[4] <= Data_fromSPI[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register7[5] <= 1'h1;
    else if (_0041_) Register7[5] <= Data_fromSPI[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register7[6] <= 1'h0;
    else if (_0041_) Register7[6] <= Data_fromSPI[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register7[7] <= 1'h0;
    else if (_0041_) Register7[7] <= Data_fromSPI[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register1[0] <= 1'h1;
    else if (_0040_) Register1[0] <= Data_fromSPI[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register1[1] <= 1'h1;
    else if (_0040_) Register1[1] <= Data_fromSPI[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register1[2] <= 1'h0;
    else if (_0040_) Register1[2] <= Data_fromSPI[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register1[3] <= 1'h1;
    else if (_0040_) Register1[3] <= Data_fromSPI[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register1[4] <= 1'h0;
    else if (_0040_) Register1[4] <= Data_fromSPI[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register1[5] <= 1'h0;
    else if (_0040_) Register1[5] <= Data_fromSPI[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register1[6] <= 1'h0;
    else if (_0040_) Register1[6] <= Data_fromSPI[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register1[7] <= 1'h0;
    else if (_0040_) Register1[7] <= Data_fromSPI[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register6[0] <= 1'h0;
    else if (_0039_) Register6[0] <= Data_fromSPI[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register6[1] <= 1'h0;
    else if (_0039_) Register6[1] <= Data_fromSPI[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register6[2] <= 1'h0;
    else if (_0039_) Register6[2] <= Data_fromSPI[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register6[3] <= 1'h0;
    else if (_0039_) Register6[3] <= Data_fromSPI[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register6[4] <= 1'h0;
    else if (_0039_) Register6[4] <= Data_fromSPI[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register6[5] <= 1'h1;
    else if (_0039_) Register6[5] <= Data_fromSPI[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register6[6] <= 1'h0;
    else if (_0039_) Register6[6] <= Data_fromSPI[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register6[7] <= 1'h0;
    else if (_0039_) Register6[7] <= Data_fromSPI[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register0[0] <= 1'h0;
    else if (_0038_) Register0[0] <= Data_fromSPI[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register0[1] <= 1'h1;
    else if (_0038_) Register0[1] <= Data_fromSPI[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register0[2] <= 1'h0;
    else if (_0038_) Register0[2] <= Data_fromSPI[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register0[3] <= 1'h1;
    else if (_0038_) Register0[3] <= Data_fromSPI[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register0[4] <= 1'h0;
    else if (_0038_) Register0[4] <= Data_fromSPI[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register0[5] <= 1'h0;
    else if (_0038_) Register0[5] <= Data_fromSPI[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register0[6] <= 1'h0;
    else if (_0038_) Register0[6] <= Data_fromSPI[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register0[7] <= 1'h0;
    else if (_0038_) Register0[7] <= Data_fromSPI[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) BitCnt[0] <= 1'h0;
    else if (_0037_) BitCnt[0] <= _0000_[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) BitCnt[1] <= 1'h0;
    else if (_0037_) BitCnt[1] <= _0000_[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) BitCnt[2] <= 1'h0;
    else if (_0037_) BitCnt[2] <= _0000_[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) BitCnt[3] <= 1'h0;
    else if (_0037_) BitCnt[3] <= _0000_[3];
  reg \debug_reg[3] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \debug_reg[3]  <= 1'h0;
    else if (_0036_) \debug_reg[3]  <= _0006_[3];
  assign debug[3] = \debug_reg[3] ;
  reg \debug_reg[0] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \debug_reg[0]  <= 1'h0;
    else if (_0035_) \debug_reg[0]  <= _0006_[0];
  assign debug[0] = \debug_reg[0] ;
  reg \debug_reg[1] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \debug_reg[1]  <= 1'h0;
    else if (_0034_) \debug_reg[1]  <= _0006_[1];
  assign debug[1] = \debug_reg[1] ;
  reg \debug_reg[2] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \debug_reg[2]  <= 1'h0;
    else if (_0033_) \debug_reg[2]  <= _0006_[2];
  assign debug[2] = \debug_reg[2] ;
  reg \debug_reg[4] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) \debug_reg[4]  <= 1'h0;
    else if (_0032_) \debug_reg[4]  <= _0006_[4];
  assign debug[4] = \debug_reg[4] ;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register5[0] <= 1'h0;
    else if (_0031_) Register5[0] <= Data_fromSPI[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register5[1] <= 1'h0;
    else if (_0031_) Register5[1] <= Data_fromSPI[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register5[2] <= 1'h0;
    else if (_0031_) Register5[2] <= Data_fromSPI[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register5[3] <= 1'h0;
    else if (_0031_) Register5[3] <= Data_fromSPI[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register5[4] <= 1'h1;
    else if (_0031_) Register5[4] <= Data_fromSPI[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register5[5] <= 1'h0;
    else if (_0031_) Register5[5] <= Data_fromSPI[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register5[6] <= 1'h0;
    else if (_0031_) Register5[6] <= Data_fromSPI[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register5[7] <= 1'h0;
    else if (_0031_) Register5[7] <= Data_fromSPI[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_toSPI[0] <= 1'h0;
    else if (RnW) Data_toSPI[0] <= _0378_[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_toSPI[1] <= 1'h0;
    else if (RnW) Data_toSPI[1] <= _0378_[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_toSPI[2] <= 1'h0;
    else if (RnW) Data_toSPI[2] <= _0378_[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_toSPI[3] <= 1'h0;
    else if (RnW) Data_toSPI[3] <= _0378_[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_toSPI[4] <= 1'h0;
    else if (RnW) Data_toSPI[4] <= _0378_[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_toSPI[5] <= 1'h0;
    else if (RnW) Data_toSPI[5] <= _0378_[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_toSPI[6] <= 1'h0;
    else if (RnW) Data_toSPI[6] <= _0378_[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Data_toSPI[7] <= 1'h0;
    else if (RnW) Data_toSPI[7] <= _0378_[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) MISO <= 1'h0;
    else if (_0028_) MISO <= _0366_;
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register4[0] <= 1'h0;
    else if (_0030_) Register4[0] <= Data_fromSPI[0];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register4[1] <= 1'h1;
    else if (_0030_) Register4[1] <= Data_fromSPI[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register4[2] <= 1'h1;
    else if (_0030_) Register4[2] <= Data_fromSPI[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register4[3] <= 1'h1;
    else if (_0030_) Register4[3] <= Data_fromSPI[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register4[4] <= 1'h0;
    else if (_0030_) Register4[4] <= Data_fromSPI[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register4[5] <= 1'h0;
    else if (_0030_) Register4[5] <= Data_fromSPI[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register4[6] <= 1'h0;
    else if (_0030_) Register4[6] <= Data_fromSPI[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) Register4[7] <= 1'h0;
    else if (_0030_) Register4[7] <= Data_fromSPI[7];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) DataToSend[0] <= 1'h0;
    else if (_0028_) DataToSend[0] <= _0352_[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) DataToSend[1] <= 1'h0;
    else if (_0028_) DataToSend[1] <= _0381_[1];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) DataToSend[2] <= 1'h0;
    else if (_0028_) DataToSend[2] <= _0381_[2];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) DataToSend[3] <= 1'h0;
    else if (_0028_) DataToSend[3] <= _0381_[3];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) DataToSend[4] <= 1'h0;
    else if (_0028_) DataToSend[4] <= _0381_[4];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) DataToSend[5] <= 1'h0;
    else if (_0028_) DataToSend[5] <= _0381_[5];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) DataToSend[6] <= 1'h0;
    else if (_0028_) DataToSend[6] <= _0381_[6];
  (* src = "../spi_slave.v:43.1-205.4" *)
  always @(posedge Clk, negedge iRST_N)
    if (!iRST_N) DataToSend[7] <= 1'h0;
    else if (_0028_) DataToSend[7] <= _0381_[7];
  assign _0383_[0] = ~BitCnt[0];
  assign _0048_ = ~SPI_State[1];
  assign _0049_ = ~SPI_State[0];
  assign _0050_ = ~SPI_State[2];
  assign _0051_ = ~Add_SPI[0];
  assign _0053_ = ~Add_SPI[2];
  assign _0052_ = ~Add_SPI[1];
  assign _0054_ = ~BitCnt[3];
  assign _0055_ = ~Add2_in[0];
  assign _0056_ = ~Add2_in[1];
  assign _0057_ = ~Add2_in[2];
  assign _0058_ = ~_0008_;
  assign _0059_ = ~_0009_;
  assign _0384_[1] = BitCnt[1] ^(* src = "../spi_slave.v:186.17-186.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  BitCnt[0];
  assign _0384_[2] = BitCnt[2] ^(* src = "../spi_slave.v:186.17-186.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0382_[1];
  assign _0384_[3] = BitCnt[3] ^(* src = "../spi_slave.v:186.17-186.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0382_[2];
  assign _0382_[2] = BitCnt[2] &(* src = "../spi_slave.v:186.17-186.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0382_[1];
  assign _0382_[1] = BitCnt[1] &(* src = "../spi_slave.v:186.17-186.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:240.19-240.41" *)  BitCnt[0];
  assign _0061_[0] = _0060_[0] |(* src = "../spi_slave.v:115.34-115.34|../spi_slave.v:109.3-119.10" *)  _0060_[1];
  assign _0187_ = _0061_[0] |(* src = "../spi_slave.v:115.34-115.34|../spi_slave.v:109.3-119.10" *)  _0061_[1];
  assign _0063_[0] = _0062_[0] |(* src = "../spi_slave.v:114.34-114.34|../spi_slave.v:109.3-119.10" *)  _0060_[1];
  assign _0188_ = _0063_[0] |(* src = "../spi_slave.v:114.34-114.34|../spi_slave.v:109.3-119.10" *)  _0061_[1];
  assign _0060_[1] = _0057_ |(* src = "../spi_slave.v:113.34-113.34|../spi_slave.v:109.3-119.10" *)  Add2_in[3];
  assign _0065_[0] = _0064_[0] |(* src = "../spi_slave.v:113.34-113.34|../spi_slave.v:109.3-119.10" *)  _0060_[1];
  assign _0189_ = _0065_[0] |(* src = "../spi_slave.v:113.34-113.34|../spi_slave.v:109.3-119.10" *)  _0061_[1];
  assign _0066_[0] = _0055_ |(* src = "../spi_slave.v:112.34-112.34|../spi_slave.v:109.3-119.10" *)  _0056_;
  assign _0067_[0] = _0066_[0] |(* src = "../spi_slave.v:112.34-112.34|../spi_slave.v:109.3-119.10" *)  _0066_[1];
  assign _0190_ = _0067_[0] |(* src = "../spi_slave.v:112.34-112.34|../spi_slave.v:109.3-119.10" *)  _0061_[1];
  assign _0060_[0] = Add2_in[0] |(* src = "../spi_slave.v:111.34-111.34|../spi_slave.v:109.3-119.10" *)  _0056_;
  assign _0068_[0] = _0060_[0] |(* src = "../spi_slave.v:111.34-111.34|../spi_slave.v:109.3-119.10" *)  _0066_[1];
  assign _0191_ = _0068_[0] |(* src = "../spi_slave.v:111.34-111.34|../spi_slave.v:109.3-119.10" *)  _0061_[1];
  assign _0062_[0] = _0055_ |(* src = "../spi_slave.v:110.34-110.34|../spi_slave.v:109.3-119.10" *)  Add2_in[1];
  assign _0069_[0] = _0062_[0] |(* src = "../spi_slave.v:110.34-110.34|../spi_slave.v:109.3-119.10" *)  _0066_[1];
  assign _0192_ = _0069_[0] |(* src = "../spi_slave.v:110.34-110.34|../spi_slave.v:109.3-119.10" *)  _0061_[1];
  assign _0070_[1] = _0053_ |(* src = "../spi_slave.v:102.39-102.39|../spi_slave.v:95.4-104.11" *)  Add_SPI[3];
  assign _0071_[0] = _0070_[0] |(* src = "../spi_slave.v:102.39-102.39|../spi_slave.v:95.4-104.11" *)  _0070_[1];
  assign _0193_ = _0071_[0] |(* src = "../spi_slave.v:102.39-102.39|../spi_slave.v:95.4-104.11" *)  _0071_[1];
  assign _0070_[2] = Add_SPI[4] |(* src = "../spi_slave.v:101.39-101.39|../spi_slave.v:95.4-104.11" *)  Add_SPI[5];
  assign _0073_[0] = _0072_[0] |(* src = "../spi_slave.v:101.39-101.39|../spi_slave.v:95.4-104.11" *)  _0070_[1];
  assign _0194_ = _0073_[0] |(* src = "../spi_slave.v:101.39-101.39|../spi_slave.v:95.4-104.11" *)  _0071_[1];
  assign _0075_[0] = _0074_[0] |(* src = "../spi_slave.v:100.39-100.39|../spi_slave.v:95.4-104.11" *)  _0070_[1];
  assign _0195_ = _0075_[0] |(* src = "../spi_slave.v:100.39-100.39|../spi_slave.v:95.4-104.11" *)  _0071_[1];
  assign _0077_[0] = _0076_[0] |(* src = "../spi_slave.v:99.39-99.39|../spi_slave.v:95.4-104.11" *)  _0070_[1];
  assign _0196_ = _0077_[0] |(* src = "../spi_slave.v:99.39-99.39|../spi_slave.v:95.4-104.11" *)  _0071_[1];
  assign _0070_[0] = _0051_ |(* src = "../spi_slave.v:98.39-98.39|../spi_slave.v:95.4-104.11" *)  _0052_;
  assign _0079_[0] = _0070_[0] |(* src = "../spi_slave.v:98.39-98.39|../spi_slave.v:95.4-104.11" *)  _0078_[1];
  assign _0071_[1] = _0070_[2] |(* src = "../spi_slave.v:98.39-98.39|../spi_slave.v:95.4-104.11" *)  Add_SPI[6];
  assign _0197_ = _0079_[0] |(* src = "../spi_slave.v:98.39-98.39|../spi_slave.v:95.4-104.11" *)  _0071_[1];
  assign _0072_[0] = Add_SPI[0] |(* src = "../spi_slave.v:97.39-97.39|../spi_slave.v:95.4-104.11" *)  _0052_;
  assign _0078_[1] = Add_SPI[2] |(* src = "../spi_slave.v:97.39-97.39|../spi_slave.v:95.4-104.11" *)  Add_SPI[3];
  assign _0080_[0] = _0072_[0] |(* src = "../spi_slave.v:97.39-97.39|../spi_slave.v:95.4-104.11" *)  _0078_[1];
  assign _0198_ = _0080_[0] |(* src = "../spi_slave.v:97.39-97.39|../spi_slave.v:95.4-104.11" *)  _0071_[1];
  assign _0074_[0] = _0051_ |(* src = "../spi_slave.v:96.39-96.39|../spi_slave.v:95.4-104.11" *)  Add_SPI[1];
  assign _0081_[0] = _0074_[0] |(* src = "../spi_slave.v:96.39-96.39|../spi_slave.v:95.4-104.11" *)  _0078_[1];
  assign _0199_ = _0081_[0] |(* src = "../spi_slave.v:96.39-96.39|../spi_slave.v:95.4-104.11" *)  _0071_[1];
  assign _0015_ = _0082_ |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0050_;
  assign _0083_ = SPI_State[0] |(* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *)  _0048_;
  assign _0011_ = _0083_ |(* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *)  SPI_State[2];
  assign _0084_ = _0049_ |(* src = "../spi_slave.v:141.7-141.7|../spi_slave.v:134.3-201.10" *)  SPI_State[1];
  assign _0012_ = _0084_ |(* src = "../spi_slave.v:141.7-141.7|../spi_slave.v:134.3-201.10" *)  SPI_State[2];
  assign _0085_ = _0049_ |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0048_;
  assign _0014_ = _0085_ |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  SPI_State[2];
  assign _0086_[0] = _0026_ & _0025_;
  assign _0086_[1] = _0024_ & _0023_;
  assign _0087_ = _0086_[0] & _0086_[1];
  assign _0046_ = _0087_ & _0022_;
  assign _0026_ = _0058_ | _0184_[1];
  assign _0045_ = _0027_ & _0009_;
  assign _0027_ = _0059_ | _0185_[1];
  assign _0044_ = _0026_ & _0008_;
  assign _0043_ = _0088_ & _0360_;
  assign _0042_ = _0088_ & _0361_;
  assign _0041_ = _0088_ & _0356_;
  assign _0089_[0] = _0010_ | _0016_;
  assign _0090_ = _0089_[0] | _0089_[1];
  assign _0025_ = _0090_ | _0019_;
  assign _0024_ = _0184_[1] | _0012_;
  assign _0023_ = _0186_[0] | _0013_;
  assign _0022_ = SSEL_delay0 | _0015_;
  assign _0040_ = _0088_ & _0362_;
  assign _0039_ = _0088_ & _0357_;
  assign _0038_ = _0088_ & _0363_;
  assign _0037_ = _0021_ & _0020_;
  assign _0009_ = _0016_ | _0017_;
  assign _0091_[1] = _0018_ | _0019_;
  assign _0021_ = _0009_ | _0091_[1];
  assign _0020_ = _0007_ | _0014_;
  assign _0092_[0] = _0019_ & _0015_;
  assign _0092_[1] = _0013_ & _0012_;
  assign _0093_ = _0092_[0] & _0092_[1];
  assign _0036_ = _0093_ & _0011_;
  assign _0094_[0] = _0018_ & _0015_;
  assign _0094_[1] = _0014_ & _0012_;
  assign _0095_ = _0094_[0] & _0094_[1];
  assign _0035_ = _0095_ & _0011_;
  assign _0096_[0] = _0017_ & _0015_;
  assign _0097_ = _0096_[0] & _0096_[1];
  assign _0034_ = _0097_ & _0011_;
  assign _0098_[0] = _0016_ & _0015_;
  assign _0099_ = _0098_[0] & _0096_[1];
  assign _0033_ = _0099_ & _0012_;
  assign _0096_[1] = _0014_ & _0013_;
  assign _0100_[1] = _0012_ & _0011_;
  assign _0101_ = _0096_[1] & _0100_[1];
  assign _0032_ = _0101_ & _0010_;
  assign _0031_ = _0088_ & _0358_;
  assign _0028_ = _0019_ & _0007_;
  assign _0088_ = _0047_ & WrEn;
  assign _0030_ = _0088_ & _0359_;
  assign _0029_ = _0017_ & _0184_[1];
  assign _0102_[0] = BitCnt[0] |(* src = "../spi_slave.v:189.9-189.23" *)  BitCnt[1];
  assign _0102_[1] = BitCnt[2] |(* src = "../spi_slave.v:189.9-189.23" *)  _0054_;
  assign _0200_ = _0102_[0] |(* src = "../spi_slave.v:189.9-189.23" *)  _0102_[1];
  assign _0103_[0] = _0066_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0060_[1];
  assign _0201_ = _0103_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0061_[1];
  assign _0183_[2] = _0342_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0343_;
  assign _0183_[3] = _0344_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0345_;
  assign _0104_[0] = _0183_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0183_[1];
  assign _0104_[1] = _0183_[2] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0183_[3];
  assign _0105_ = _0104_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0104_[1];
  assign _0106_[0] = _0202_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0203_;
  assign _0106_[1] = _0204_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0205_;
  assign _0106_[2] = _0206_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0207_;
  assign _0106_[3] = _0208_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0209_;
  assign _0107_[0] = _0106_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0106_[1];
  assign _0107_[1] = _0106_[2] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0106_[3];
  assign _0108_ = _0107_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0107_[1];
  assign _0109_[0] = _0210_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0211_;
  assign _0109_[1] = _0212_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0213_;
  assign _0109_[2] = _0214_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0215_;
  assign _0109_[3] = _0216_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0217_;
  assign _0110_[0] = _0109_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0109_[1];
  assign _0110_[1] = _0109_[2] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0109_[3];
  assign _0111_ = _0110_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0110_[1];
  assign _0112_[0] = _0218_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0219_;
  assign _0112_[1] = _0220_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0221_;
  assign _0112_[2] = _0222_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0223_;
  assign _0112_[3] = _0224_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0225_;
  assign _0113_[0] = _0112_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0112_[1];
  assign _0113_[1] = _0112_[2] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0112_[3];
  assign _0114_ = _0113_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0113_[1];
  assign _0115_[0] = _0226_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0227_;
  assign _0115_[1] = _0228_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0229_;
  assign _0115_[2] = _0230_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0231_;
  assign _0115_[3] = _0232_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0233_;
  assign _0116_[0] = _0115_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0115_[1];
  assign _0116_[1] = _0115_[2] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0115_[3];
  assign _0117_ = _0116_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0116_[1];
  assign _0118_[0] = _0234_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0235_;
  assign _0118_[1] = _0236_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0237_;
  assign _0118_[2] = _0238_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0239_;
  assign _0118_[3] = _0240_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0241_;
  assign _0119_[0] = _0118_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0118_[1];
  assign _0119_[1] = _0118_[2] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0118_[3];
  assign _0120_ = _0119_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0119_[1];
  assign _0121_[0] = _0242_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0243_;
  assign _0121_[1] = _0244_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0245_;
  assign _0121_[2] = _0246_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0247_;
  assign _0121_[3] = _0248_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0249_;
  assign _0122_[0] = _0121_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0121_[1];
  assign _0122_[1] = _0121_[2] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0121_[3];
  assign _0123_ = _0122_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0122_[1];
  assign _0064_[0] = Add2_in[0] |(* src = "../spi_slave.v:109.17-109.17|../spi_slave.v:109.3-119.10" *)  Add2_in[1];
  assign _0066_[1] = Add2_in[2] |(* src = "../spi_slave.v:109.17-109.17|../spi_slave.v:109.3-119.10" *)  Add2_in[3];
  assign _0060_[2] = Add2_in[4] |(* src = "../spi_slave.v:109.17-109.17|../spi_slave.v:109.3-119.10" *)  Add2_in[5];
  assign _0060_[3] = Add2_in[6] |(* src = "../spi_slave.v:109.17-109.17|../spi_slave.v:109.3-119.10" *)  Add2_in[7];
  assign _0124_[0] = _0064_[0] |(* src = "../spi_slave.v:109.17-109.17|../spi_slave.v:109.3-119.10" *)  _0066_[1];
  assign _0061_[1] = _0060_[2] |(* src = "../spi_slave.v:109.17-109.17|../spi_slave.v:109.3-119.10" *)  _0060_[3];
  assign _0125_ = _0124_[0] |(* src = "../spi_slave.v:109.17-109.17|../spi_slave.v:109.3-119.10" *)  _0061_[1];
  assign _0126_[1] = _0008_ |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0010_;
  assign _0127_ = _0089_[1] |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0126_[1];
  assign _0128_[0] = _0250_ |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0251_;
  assign _0129_ = _0128_[0] |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0128_[1];
  assign _0130_[0] = _0254_ |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0255_;
  assign _0128_[1] = _0252_ |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0253_;
  assign _0131_ = _0130_[0] |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0128_[1];
  assign _0132_[0] = _0254_ |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0256_;
  assign _0132_[1] = _0257_ |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0253_;
  assign _0133_ = _0132_[0] |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0132_[1];
  assign _0134_[0] = _0356_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0357_;
  assign _0134_[1] = _0358_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0359_;
  assign _0134_[2] = _0360_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0361_;
  assign _0134_[3] = _0362_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0363_;
  assign _0135_[0] = _0134_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0134_[1];
  assign _0135_[1] = _0134_[2] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0134_[3];
  assign _0136_ = _0135_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0135_[1];
  assign _0137_[0] = _0258_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0259_;
  assign _0137_[1] = _0260_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0261_;
  assign _0137_[2] = _0262_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0263_;
  assign _0137_[3] = _0264_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0265_;
  assign _0138_[0] = _0137_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0137_[1];
  assign _0138_[1] = _0137_[2] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0137_[3];
  assign _0139_ = _0138_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0138_[1];
  assign _0140_[0] = _0266_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0267_;
  assign _0140_[1] = _0268_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0269_;
  assign _0140_[2] = _0270_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0271_;
  assign _0140_[3] = _0272_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0273_;
  assign _0141_[0] = _0140_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0140_[1];
  assign _0141_[1] = _0140_[2] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0140_[3];
  assign _0142_ = _0141_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0141_[1];
  assign _0143_[0] = _0274_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0275_;
  assign _0143_[1] = _0276_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0277_;
  assign _0143_[2] = _0278_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0279_;
  assign _0143_[3] = _0280_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0281_;
  assign _0144_[0] = _0143_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0143_[1];
  assign _0144_[1] = _0143_[2] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0143_[3];
  assign _0145_ = _0144_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0144_[1];
  assign _0146_[0] = _0282_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0283_;
  assign _0146_[1] = _0284_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0285_;
  assign _0146_[2] = _0286_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0287_;
  assign _0146_[3] = _0288_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0289_;
  assign _0147_[0] = _0146_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0146_[1];
  assign _0147_[1] = _0146_[2] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0146_[3];
  assign _0148_ = _0147_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0147_[1];
  assign _0149_[0] = _0290_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0291_;
  assign _0149_[1] = _0292_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0293_;
  assign _0149_[2] = _0294_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0295_;
  assign _0149_[3] = _0296_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0297_;
  assign _0150_[0] = _0149_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0149_[1];
  assign _0150_[1] = _0149_[2] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0149_[3];
  assign _0151_ = _0150_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0150_[1];
  assign _0152_[0] = _0298_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0299_;
  assign _0152_[1] = _0300_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0301_;
  assign _0152_[2] = _0302_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0303_;
  assign _0152_[3] = _0304_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0305_;
  assign _0153_[0] = _0152_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0152_[1];
  assign _0153_[1] = _0152_[2] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0152_[3];
  assign _0154_ = _0153_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0153_[1];
  assign _0155_[0] = _0306_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0307_;
  assign _0155_[1] = _0308_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0309_;
  assign _0155_[2] = _0310_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0311_;
  assign _0155_[3] = _0312_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0313_;
  assign _0156_[0] = _0155_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0155_[1];
  assign _0156_[1] = _0155_[2] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0155_[3];
  assign _0157_ = _0156_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0156_[1];
  assign _0158_[0] = _0314_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0315_;
  assign _0158_[1] = _0316_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0317_;
  assign _0158_[2] = _0318_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0319_;
  assign _0158_[3] = _0320_ |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0321_;
  assign _0159_[0] = _0158_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0158_[1];
  assign _0159_[1] = _0158_[2] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0158_[3];
  assign _0160_ = _0159_[0] |(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0159_[1];
  assign _0008_ = _0019_ |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0016_;
  assign _0089_[1] = _0017_ |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0018_;
  assign _0161_ = _0008_ |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0089_[1];
  assign _0162_[0] = _0322_ |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0323_;
  assign _0163_ = _0162_[0] |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0162_[1];
  assign _0164_[0] = _0324_ |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0325_;
  assign _0165_ = _0164_[0] |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0164_[1];
  assign _0166_[0] = _0326_ |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0327_;
  assign _0167_ = _0166_[0] |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0166_[1];
  assign _0168_[0] = _0328_ |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0329_;
  assign _0169_ = _0168_[0] |(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0168_[1];
  assign _0076_[0] = Add_SPI[0] |(* src = "../spi_slave.v:95.18-95.18|../spi_slave.v:95.4-104.11" *)  Add_SPI[1];
  assign _0170_[0] = _0076_[0] |(* src = "../spi_slave.v:95.18-95.18|../spi_slave.v:95.4-104.11" *)  _0078_[1];
  assign _0171_ = _0170_[0] |(* src = "../spi_slave.v:95.18-95.18|../spi_slave.v:95.4-104.11" *)  _0071_[1];
  assign _0172_[0] = _0010_ |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0019_;
  assign _0173_ = _0172_[0] |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0009_;
  assign _0174_ = _0173_ |(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0018_;
  assign _0082_ = SPI_State[0] |(* src = "../spi_slave.v:134.19-134.19|../spi_slave.v:134.3-201.10" *)  SPI_State[1];
  assign _0013_ = _0082_ |(* src = "../spi_slave.v:134.19-134.19|../spi_slave.v:134.3-201.10" *)  SPI_State[2];
  assign _0175_[1] = BitCnt[2] |(* src = "../spi_slave.v:175.9-175.20" *)  BitCnt[3];
  assign _0176_ = _0102_[0] |(* src = "../spi_slave.v:175.9-175.20" *)  _0175_[1];
  assign _0177_[0] = _0367_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0368_;
  assign _0177_[1] = _0369_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0370_;
  assign _0177_[2] = _0371_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0372_;
  assign _0177_[3] = _0373_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0374_;
  assign _0178_[0] = _0177_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0177_[1];
  assign _0178_[1] = _0177_[2] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0177_[3];
  assign _0179_ = _0178_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0178_[1];
  assign _0180_[0] = _0330_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0331_;
  assign _0180_[1] = _0332_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0333_;
  assign _0180_[2] = _0334_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0335_;
  assign _0180_[3] = _0336_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0337_;
  assign _0181_[0] = _0180_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0180_[1];
  assign _0181_[1] = _0180_[2] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0180_[3];
  assign _0182_ = _0181_[0] |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0181_[1];
  assign _0183_[0] = _0338_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0339_;
  assign _0183_[1] = _0340_ |(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0341_;
  assign _0368_ = ~(* src = "../spi_slave.v:115.34-115.34|../spi_slave.v:109.3-119.10" *) _0187_;
  assign _0369_ = ~(* src = "../spi_slave.v:114.34-114.34|../spi_slave.v:109.3-119.10" *) _0188_;
  assign _0370_ = ~(* src = "../spi_slave.v:113.34-113.34|../spi_slave.v:109.3-119.10" *) _0189_;
  assign _0371_ = ~(* src = "../spi_slave.v:112.34-112.34|../spi_slave.v:109.3-119.10" *) _0190_;
  assign _0372_ = ~(* src = "../spi_slave.v:111.34-111.34|../spi_slave.v:109.3-119.10" *) _0191_;
  assign _0373_ = ~(* src = "../spi_slave.v:110.34-110.34|../spi_slave.v:109.3-119.10" *) _0192_;
  assign _0374_ = ~(* src = "../spi_slave.v:109.17-109.17|../spi_slave.v:109.3-119.10" *) _0125_;
  assign _0356_ = ~(* src = "../spi_slave.v:102.39-102.39|../spi_slave.v:95.4-104.11" *) _0193_;
  assign _0357_ = ~(* src = "../spi_slave.v:101.39-101.39|../spi_slave.v:95.4-104.11" *) _0194_;
  assign _0358_ = ~(* src = "../spi_slave.v:100.39-100.39|../spi_slave.v:95.4-104.11" *) _0195_;
  assign _0359_ = ~(* src = "../spi_slave.v:99.39-99.39|../spi_slave.v:95.4-104.11" *) _0196_;
  assign _0360_ = ~(* src = "../spi_slave.v:98.39-98.39|../spi_slave.v:95.4-104.11" *) _0197_;
  assign _0361_ = ~(* src = "../spi_slave.v:97.39-97.39|../spi_slave.v:95.4-104.11" *) _0198_;
  assign _0362_ = ~(* src = "../spi_slave.v:96.39-96.39|../spi_slave.v:95.4-104.11" *) _0199_;
  assign _0363_ = ~(* src = "../spi_slave.v:95.18-95.18|../spi_slave.v:95.4-104.11" *) _0171_;
  assign _0010_ = ~(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *) _0015_;
  assign _0016_ = ~(* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *) _0011_;
  assign _0017_ = ~(* src = "../spi_slave.v:141.7-141.7|../spi_slave.v:134.3-201.10" *) _0012_;
  assign _0018_ = ~(* src = "../spi_slave.v:134.19-134.19|../spi_slave.v:134.3-201.10" *) _0013_;
  assign _0019_ = ~(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0014_;
  assign _0367_ = ~(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *) _0201_;
  assign _0186_[0] = _0346_ &(* src = "../spi_slave.v:139.9-139.46" *)  SSEL_delay1;
  assign _0185_[1] = SCK_delay0 &(* src = "../spi_slave.v:162.9-162.43" *)  _0347_;
  assign _0007_ = _0348_ &(* src = "../spi_slave.v:183.10-183.44" *)  SCK_delay1;
  assign _0184_[1] = ~(* src = "../spi_slave.v:166.9-166.23|../spi_slave.v:166.5-170.8" *) _0200_;
  assign _0005_ = _0011_ ? (* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *) 1'h0 : _0184_[1];
  assign _0375_[0] = SSEL_delay0 ? (* src = "../spi_slave.v:197.9-197.20|../spi_slave.v:197.5-198.24" *) 1'h0 : 1'hx;
  assign _0376_[0] = _0200_ ? (* src = "../spi_slave.v:166.9-166.23|../spi_slave.v:166.5-170.8" *) 1'hx : 1'h0;
  assign _0349_[7] = _0200_ ? (* src = "../spi_slave.v:149.9-149.23|../spi_slave.v:149.5-157.8" *) 1'hx : ReceivedByte[7];
  assign _0376_[2] = _0200_ ? (* src = "../spi_slave.v:149.9-149.23|../spi_slave.v:149.5-157.8" *) 1'hx : 1'h1;
  assign _0377_[0] = _0186_[0] ? (* src = "../spi_slave.v:139.9-139.46|../spi_slave.v:139.5-140.24" *) 1'h1 : 1'hx;
  assign _0377_[1] = _0186_[0] ? (* src = "../spi_slave.v:139.9-139.46|../spi_slave.v:139.5-140.24" *) 1'h0 : 1'hx;
  assign _0379_[1] = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) DataToSend[0] : 1'hx;
  assign _0379_[2] = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) DataToSend[1] : 1'hx;
  assign _0379_[3] = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) DataToSend[2] : 1'hx;
  assign _0379_[4] = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) DataToSend[3] : 1'hx;
  assign _0379_[5] = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) DataToSend[4] : 1'hx;
  assign _0379_[6] = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) DataToSend[5] : 1'hx;
  assign _0379_[7] = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) DataToSend[6] : 1'hx;
  assign _0380_[1] = _0007_ ? (* src = "../spi_slave.v:176.10-176.44|../spi_slave.v:176.6-180.9" *) Data_toSPI[0] : 1'hx;
  assign _0380_[2] = _0007_ ? (* src = "../spi_slave.v:176.10-176.44|../spi_slave.v:176.6-180.9" *) Data_toSPI[1] : 1'hx;
  assign _0380_[3] = _0007_ ? (* src = "../spi_slave.v:176.10-176.44|../spi_slave.v:176.6-180.9" *) Data_toSPI[2] : 1'hx;
  assign _0380_[4] = _0007_ ? (* src = "../spi_slave.v:176.10-176.44|../spi_slave.v:176.6-180.9" *) Data_toSPI[3] : 1'hx;
  assign _0380_[5] = _0007_ ? (* src = "../spi_slave.v:176.10-176.44|../spi_slave.v:176.6-180.9" *) Data_toSPI[4] : 1'hx;
  assign _0380_[6] = _0007_ ? (* src = "../spi_slave.v:176.10-176.44|../spi_slave.v:176.6-180.9" *) Data_toSPI[5] : 1'hx;
  assign _0380_[7] = _0007_ ? (* src = "../spi_slave.v:176.10-176.44|../spi_slave.v:176.6-180.9" *) Data_toSPI[6] : 1'hx;
  assign _0381_[1] = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0379_[1] : _0380_[1];
  assign _0381_[2] = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0379_[2] : _0380_[2];
  assign _0381_[3] = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0379_[3] : _0380_[3];
  assign _0381_[4] = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0379_[4] : _0380_[4];
  assign _0381_[5] = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0379_[5] : _0380_[5];
  assign _0381_[6] = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0379_[6] : _0380_[6];
  assign _0381_[7] = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0379_[7] : _0380_[7];
  assign _0002_[0] = _0008_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0349_[0] : 1'hx;
  assign _0002_[1] = _0008_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0349_[1] : 1'hx;
  assign _0002_[2] = _0008_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0349_[2] : 1'hx;
  assign _0002_[3] = _0008_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0349_[3] : 1'hx;
  assign _0002_[4] = _0008_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0349_[4] : 1'hx;
  assign _0002_[5] = _0008_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0349_[5] : 1'hx;
  assign _0002_[6] = _0008_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0349_[6] : 1'hx;
  assign _0002_[7] = _0008_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0349_[7] : 1'hx;
  assign _0349_[0] = _0200_ ? (* src = "../spi_slave.v:166.9-166.23|../spi_slave.v:166.5-170.8" *) 1'hx : ReceivedByte[0];
  assign _0349_[1] = _0200_ ? (* src = "../spi_slave.v:166.9-166.23|../spi_slave.v:166.5-170.8" *) 1'hx : ReceivedByte[1];
  assign _0349_[2] = _0200_ ? (* src = "../spi_slave.v:166.9-166.23|../spi_slave.v:166.5-170.8" *) 1'hx : ReceivedByte[2];
  assign _0349_[3] = _0200_ ? (* src = "../spi_slave.v:166.9-166.23|../spi_slave.v:166.5-170.8" *) 1'hx : ReceivedByte[3];
  assign _0349_[4] = _0200_ ? (* src = "../spi_slave.v:166.9-166.23|../spi_slave.v:166.5-170.8" *) 1'hx : ReceivedByte[4];
  assign _0349_[5] = _0200_ ? (* src = "../spi_slave.v:166.9-166.23|../spi_slave.v:166.5-170.8" *) 1'hx : ReceivedByte[5];
  assign _0349_[6] = _0200_ ? (* src = "../spi_slave.v:166.9-166.23|../spi_slave.v:166.5-170.8" *) 1'hx : ReceivedByte[6];
  assign _0003_[0] = _0009_ ? (* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *) _0350_[0] : 1'hx;
  assign _0003_[1] = _0009_ ? (* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *) _0350_[1] : 1'hx;
  assign _0003_[2] = _0009_ ? (* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *) _0350_[2] : 1'hx;
  assign _0003_[3] = _0009_ ? (* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *) _0350_[3] : 1'hx;
  assign _0003_[4] = _0009_ ? (* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *) _0350_[4] : 1'hx;
  assign _0003_[5] = _0009_ ? (* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *) _0350_[5] : 1'hx;
  assign _0003_[6] = _0009_ ? (* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *) _0350_[6] : 1'hx;
  assign _0003_[7] = _0009_ ? (* src = "../spi_slave.v:158.7-158.7|../spi_slave.v:134.3-201.10" *) _0350_[7] : 1'hx;
  assign _0350_[0] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) MOSI_delay0 : 1'hx;
  assign _0350_[1] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) ReceivedByte[0] : 1'hx;
  assign _0350_[2] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) ReceivedByte[1] : 1'hx;
  assign _0350_[3] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) ReceivedByte[2] : 1'hx;
  assign _0350_[4] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) ReceivedByte[3] : 1'hx;
  assign _0350_[5] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) ReceivedByte[4] : 1'hx;
  assign _0350_[6] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) ReceivedByte[5] : 1'hx;
  assign _0350_[7] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) ReceivedByte[6] : 1'hx;
  assign _0351_[0] = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) _0383_[0] : 1'hx;
  assign _0351_[1] = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) _0384_[1] : 1'hx;
  assign _0351_[2] = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) _0384_[2] : 1'hx;
  assign _0351_[3] = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) _0384_[3] : 1'hx;
  assign _0352_[0] = _0007_ ? (* src = "../spi_slave.v:176.10-176.44|../spi_slave.v:176.6-180.9" *) 1'h1 : 1'hx;
  assign _0352_[1] = _0007_ ? (* src = "../spi_slave.v:176.10-176.44|../spi_slave.v:176.6-180.9" *) 1'h0 : 1'hx;
  assign _0353_[0] = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0351_[0] : _0352_[0];
  assign _0353_[1] = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0351_[1] : _0352_[1];
  assign _0353_[2] = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0351_[2] : _0352_[1];
  assign _0353_[3] = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0351_[3] : _0352_[1];
  assign _0354_[0] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) _0383_[0] : BitCnt[0];
  assign _0354_[1] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) _0384_[1] : BitCnt[1];
  assign _0354_[2] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) _0384_[2] : BitCnt[2];
  assign _0354_[3] = _0185_[1] ? (* src = "../spi_slave.v:145.9-145.43|../spi_slave.v:145.5-148.8" *) _0384_[3] : BitCnt[3];
  assign _0355_[0] = _0200_ ? (* src = "../spi_slave.v:149.9-149.23|../spi_slave.v:149.5-157.8" *) _0354_[0] : 1'h0;
  assign _0355_[1] = _0200_ ? (* src = "../spi_slave.v:149.9-149.23|../spi_slave.v:149.5-157.8" *) _0354_[1] : 1'h0;
  assign _0355_[2] = _0200_ ? (* src = "../spi_slave.v:149.9-149.23|../spi_slave.v:149.5-157.8" *) _0354_[2] : 1'h0;
  assign _0355_[3] = _0200_ ? (* src = "../spi_slave.v:149.9-149.23|../spi_slave.v:149.5-157.8" *) _0354_[3] : 1'h0;
  assign _0364_ = _0007_ ? (* src = "../spi_slave.v:183.10-183.44|../spi_slave.v:183.6-187.9" *) DataToSend[7] : 1'hx;
  assign _0365_ = _0007_ ? (* src = "../spi_slave.v:176.10-176.44|../spi_slave.v:176.6-180.9" *) Data_toSPI[7] : 1'hx;
  assign _0366_ = _0176_ ? (* src = "../spi_slave.v:175.9-175.20|../spi_slave.v:175.5-188.8" *) _0364_ : _0365_;
  assign _0202_ = Register7[2] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0367_;
  assign _0203_ = Register6[2] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0368_;
  assign _0204_ = Register5[2] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0369_;
  assign _0205_ = Register4[2] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0370_;
  assign _0206_ = Register3[2] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0371_;
  assign _0207_ = Register2[2] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0372_;
  assign _0208_ = Register1[2] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0373_;
  assign _0209_ = Register0[2] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0374_;
  assign _0210_ = Register7[3] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0367_;
  assign _0211_ = Register6[3] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0368_;
  assign _0212_ = Register5[3] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0369_;
  assign _0213_ = Register4[3] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0370_;
  assign _0214_ = Register3[3] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0371_;
  assign _0215_ = Register2[3] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0372_;
  assign _0216_ = Register1[3] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0373_;
  assign _0217_ = Register0[3] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0374_;
  assign _0218_ = Register7[4] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0367_;
  assign _0219_ = Register6[4] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0368_;
  assign _0220_ = Register5[4] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0369_;
  assign _0221_ = Register4[4] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0370_;
  assign _0222_ = Register3[4] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0371_;
  assign _0223_ = Register2[4] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0372_;
  assign _0224_ = Register1[4] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0373_;
  assign _0225_ = Register0[4] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0374_;
  assign _0226_ = Register7[5] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0367_;
  assign _0227_ = Register6[5] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0368_;
  assign _0228_ = Register5[5] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0369_;
  assign _0229_ = Register4[5] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0370_;
  assign _0230_ = Register3[5] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0371_;
  assign _0231_ = Register2[5] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0372_;
  assign _0232_ = Register1[5] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0373_;
  assign _0233_ = Register0[5] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0374_;
  assign _0234_ = Register7[6] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0367_;
  assign _0235_ = Register6[6] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0368_;
  assign _0236_ = Register5[6] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0369_;
  assign _0237_ = Register4[6] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0370_;
  assign _0238_ = Register3[6] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0371_;
  assign _0239_ = Register2[6] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0372_;
  assign _0240_ = Register1[6] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0373_;
  assign _0241_ = Register0[6] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0374_;
  assign _0242_ = Register7[7] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0367_;
  assign _0243_ = Register6[7] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0368_;
  assign _0244_ = Register5[7] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0369_;
  assign _0245_ = Register4[7] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0370_;
  assign _0246_ = Register3[7] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0371_;
  assign _0247_ = Register2[7] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0372_;
  assign _0248_ = Register1[7] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0373_;
  assign _0249_ = Register0[7] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0374_;
  assign _0250_ = _0377_[0] &(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0018_;
  assign _0251_ = _0349_[7] &(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0017_;
  assign _0255_ = _0376_[2] &(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0017_;
  assign _0252_ = _0376_[0] &(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0008_;
  assign _0254_ = _0377_[1] &(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0018_;
  assign _0256_ = _0376_[0] &(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0017_;
  assign _0257_ = _0376_[2] &(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0008_;
  assign _0253_ = _0375_[0] &(* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *)  _0010_;
  assign _0258_ = Register7[0] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0356_;
  assign _0259_ = Register6[0] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0357_;
  assign _0260_ = Register5[0] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0358_;
  assign _0261_ = Register4[0] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0359_;
  assign _0262_ = Register3[0] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0360_;
  assign _0263_ = Register2[0] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0361_;
  assign _0264_ = Register1[0] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0362_;
  assign _0265_ = Register0[0] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0363_;
  assign _0266_ = Register7[1] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0356_;
  assign _0267_ = Register6[1] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0357_;
  assign _0268_ = Register5[1] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0358_;
  assign _0269_ = Register4[1] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0359_;
  assign _0270_ = Register3[1] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0360_;
  assign _0271_ = Register2[1] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0361_;
  assign _0272_ = Register1[1] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0362_;
  assign _0273_ = Register0[1] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0363_;
  assign _0274_ = Register7[2] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0356_;
  assign _0275_ = Register6[2] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0357_;
  assign _0276_ = Register5[2] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0358_;
  assign _0277_ = Register4[2] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0359_;
  assign _0278_ = Register3[2] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0360_;
  assign _0279_ = Register2[2] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0361_;
  assign _0280_ = Register1[2] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0362_;
  assign _0281_ = Register0[2] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0363_;
  assign _0282_ = Register7[3] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0356_;
  assign _0283_ = Register6[3] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0357_;
  assign _0284_ = Register5[3] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0358_;
  assign _0285_ = Register4[3] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0359_;
  assign _0286_ = Register3[3] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0360_;
  assign _0287_ = Register2[3] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0361_;
  assign _0288_ = Register1[3] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0362_;
  assign _0289_ = Register0[3] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0363_;
  assign _0290_ = Register7[4] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0356_;
  assign _0291_ = Register6[4] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0357_;
  assign _0292_ = Register5[4] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0358_;
  assign _0293_ = Register4[4] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0359_;
  assign _0294_ = Register3[4] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0360_;
  assign _0295_ = Register2[4] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0361_;
  assign _0296_ = Register1[4] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0362_;
  assign _0297_ = Register0[4] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0363_;
  assign _0298_ = Register7[5] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0356_;
  assign _0299_ = Register6[5] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0357_;
  assign _0300_ = Register5[5] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0358_;
  assign _0301_ = Register4[5] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0359_;
  assign _0302_ = Register3[5] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0360_;
  assign _0303_ = Register2[5] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0361_;
  assign _0304_ = Register1[5] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0362_;
  assign _0305_ = Register0[5] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0363_;
  assign _0306_ = Register7[6] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0356_;
  assign _0307_ = Register6[6] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0357_;
  assign _0308_ = Register5[6] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0358_;
  assign _0309_ = Register4[6] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0359_;
  assign _0310_ = Register3[6] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0360_;
  assign _0311_ = Register2[6] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0361_;
  assign _0312_ = Register1[6] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0362_;
  assign _0313_ = Register0[6] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0363_;
  assign _0314_ = Register7[7] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0356_;
  assign _0315_ = Register6[7] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0357_;
  assign _0316_ = Register5[7] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0358_;
  assign _0317_ = Register4[7] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0359_;
  assign _0318_ = Register3[7] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0360_;
  assign _0319_ = Register2[7] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0361_;
  assign _0320_ = Register1[7] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0362_;
  assign _0321_ = Register0[7] &(* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *)  _0363_;
  assign _0322_ = _0353_[0] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0019_;
  assign _0323_ = _0354_[0] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0016_;
  assign _0162_[1] = _0355_[0] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0017_;
  assign _0324_ = _0353_[1] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0019_;
  assign _0325_ = _0354_[1] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0016_;
  assign _0164_[1] = _0355_[1] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0017_;
  assign _0326_ = _0353_[2] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0019_;
  assign _0327_ = _0354_[2] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0016_;
  assign _0166_[1] = _0355_[2] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0017_;
  assign _0328_ = _0353_[3] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0019_;
  assign _0329_ = _0354_[3] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0016_;
  assign _0168_[1] = _0355_[3] &(* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *)  _0017_;
  assign _0330_ = Register7[0] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0367_;
  assign _0331_ = Register6[0] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0368_;
  assign _0332_ = Register5[0] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0369_;
  assign _0333_ = Register4[0] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0370_;
  assign _0334_ = Register3[0] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0371_;
  assign _0335_ = Register2[0] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0372_;
  assign _0336_ = Register1[0] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0373_;
  assign _0337_ = Register0[0] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0374_;
  assign _0338_ = Register7[1] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0367_;
  assign _0339_ = Register6[1] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0368_;
  assign _0340_ = Register5[1] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0369_;
  assign _0341_ = Register4[1] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0370_;
  assign _0342_ = Register3[1] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0371_;
  assign _0343_ = Register2[1] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0372_;
  assign _0344_ = Register1[1] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0373_;
  assign _0345_ = Register0[1] &(* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *)  _0374_;
  assign _0047_ = ~RnW;
  assign _0346_ = ~(* src = "../spi_slave.v:139.9-139.25" *) SSEL_delay0;
  assign _0347_ = ~(* src = "../spi_slave.v:162.28-162.43" *) SCK_delay1;
  assign _0348_ = ~(* src = "../spi_slave.v:183.10-183.25" *) SCK_delay0;
  assign _0001_[1] = _0179_ ? (* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *) _0105_ : 1'h1;
  assign _0001_[2] = _0179_ ? (* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *) _0108_ : 1'h1;
  assign _0001_[3] = _0179_ ? (* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *) _0111_ : 1'h1;
  assign _0001_[4] = _0179_ ? (* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *) _0114_ : 1'h1;
  assign _0001_[5] = _0179_ ? (* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *) _0117_ : 1'h1;
  assign _0001_[6] = _0179_ ? (* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *) _0120_ : 1'h1;
  assign _0001_[7] = _0179_ ? (* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *) _0123_ : 1'h1;
  assign _0004_[0] = _0127_ ? (* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *) _0129_ : 1'hx;
  assign _0004_[1] = _0127_ ? (* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *) _0131_ : 1'hx;
  assign _0004_[2] = _0127_ ? (* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *) _0133_ : 1'hx;
  assign _0378_[0] = _0136_ ? (* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *) _0139_ : 1'h1;
  assign _0378_[1] = _0136_ ? (* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *) _0142_ : 1'h1;
  assign _0378_[2] = _0136_ ? (* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *) _0145_ : 1'h1;
  assign _0378_[3] = _0136_ ? (* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *) _0148_ : 1'h1;
  assign _0378_[4] = _0136_ ? (* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *) _0151_ : 1'h1;
  assign _0378_[5] = _0136_ ? (* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *) _0154_ : 1'h1;
  assign _0378_[6] = _0136_ ? (* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *) _0157_ : 1'h1;
  assign _0378_[7] = _0136_ ? (* src = "../spi_slave.v:89.36-89.36|../spi_slave.v:82.4-92.11" *) _0160_ : 1'h1;
  assign _0000_[0] = _0161_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0163_ : 1'hx;
  assign _0000_[1] = _0161_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0165_ : 1'hx;
  assign _0000_[2] = _0161_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0167_ : 1'hx;
  assign _0000_[3] = _0161_ ? (* src = "../spi_slave.v:171.7-171.7|../spi_slave.v:134.3-201.10" *) _0169_ : 1'hx;
  assign _0006_[0] = _0174_ ? (* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *) _0018_ : 1'hx;
  assign _0006_[1] = _0174_ ? (* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *) _0017_ : 1'hx;
  assign _0006_[2] = _0174_ ? (* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *) _0016_ : 1'hx;
  assign _0006_[3] = _0174_ ? (* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *) _0019_ : 1'hx;
  assign _0006_[4] = _0174_ ? (* src = "../spi_slave.v:193.7-193.7|../spi_slave.v:134.3-201.10" *) _0010_ : 1'hx;
  assign _0001_[0] = _0179_ ? (* src = "../spi_slave.v:116.34-116.34|../spi_slave.v:109.3-119.10" *) _0182_ : 1'h1;
  assign _0130_[1] = _0128_[1];
  assign { _0384_[31:4], _0384_[0] } = { 27'h0000000, _0382_[3], _0383_[0] };
  assign _0077_[1] = _0071_[1];
  assign _0126_[0] = _0089_[1];
  assign _0124_[1] = _0061_[1];
  assign _0076_[2:1] = _0070_[2:1];
  assign _0069_[1] = _0061_[1];
  assign _0170_[1] = _0071_[1];
  assign _0075_[1] = _0071_[1];
  assign _0068_[1] = _0061_[1];
  assign _0074_[2:1] = _0070_[2:1];
  assign _0383_[31:1] = { 28'h0000000, BitCnt[3:1] };
  assign _0067_[1] = _0061_[1];
  assign _0066_[3:2] = _0060_[3:2];
  assign { _0382_[31:4], _0382_[0] } = { 28'h0000000, BitCnt[0] };
  assign _0073_[1] = _0071_[1];
  assign _0065_[1] = _0061_[1];
  assign _0064_[3:1] = _0060_[3:1];
  assign _0072_[2:1] = _0070_[2:1];
  assign _0063_[1] = _0061_[1];
  assign _0062_[3:1] = _0060_[3:1];
  assign _0081_[1] = _0071_[1];
  assign _0103_[1] = _0061_[1];
  assign _0175_[0] = _0102_[0];
  assign _0080_[1] = _0071_[1];
  assign _0172_[1] = _0009_;
  assign _0100_[0] = _0096_[1];
  assign _0098_[1] = _0096_[1];
  assign _0079_[1] = _0071_[1];
  assign _0091_[0] = _0009_;
  assign { _0078_[2], _0078_[0] } = { _0070_[2], _0070_[0] };
  assign _0186_[1] = _0013_;
  assign _0185_[0] = _0059_;
  assign _0184_[0] = _0058_;
  assign _0377_[2] = _0377_[1];
  assign _0352_[3:2] = { _0352_[1], _0352_[1] };
  assign _0379_[0] = _0352_[1];
  assign _0376_[1] = _0376_[0];
  assign _0375_[2:1] = { _0375_[0], _0375_[0] };
  assign _0380_[0] = _0352_[1];
  assign _0381_[0] = _0352_[1];
  assign _0006_[7:6] = { _0006_[5], _0006_[5] };
  assign Add_SPI[7] = 1'h0;
  assign debug[7:5] = 3'h0;
endmodule
