#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

if [[ ! -f ihp_pdk.env ]]; then
  echo "ERROR: Copy ihp_pdk.env.example to ihp_pdk.env and update the IHP PDK paths."
  exit 1
fi

source ihp_pdk.env

if [[ -z "${PDK_ROOT:-}" || -z "${PDK:-}" ]]; then
  echo "ERROR: PDK_ROOT and PDK must be set in ihp_pdk.env"
  echo "Please set PDK_ROOT to your IHP PDK root and PDK to the PDK name (for example ihp-sg13g2)."
  exit 1
fi

mkdir -p work

echo "=== Running LibreLane synthesis ==="
command -v make >/dev/null 2>&1
if [[ $? -ne 0 ]]; then
  echo "ERROR: make not found in PATH"
  exit 1
fi

make librelane

if [[ -n "${DISPLAY:-}" ]]; then
  echo "=== Running LibreLane OpenROAD flow (GUI) ==="
  make librelane-openroad
else
  echo "=== DISPLAY not set; skipping OpenROAD GUI. The GDS output has already been generated by the LibreLane flow. ==="
fi

echo "=== Flow complete ==="
echo "Outputs: $(pwd)/work"
